### ISSUE TITLE
Running on TUM dataset

### ISSUE THREAD

**Issue by CharlieLeee** [heethesh/SALSA-Semantic-Assisted-SLAM#5]
@heethesh  **Hi, thanks for the inspiring work!** I would like to know the right way to run your model on the TUM dataset( e.g. walking). The following is how I'm going to try it, and please correct me if I misunderstand:

1. catkin_make `orb_slam`(I use the one in your repo)
2. segment the pictures converted from the bag (I would appreciate if the steps are offered)
3. run updata_rosbag to apply the semantic segmentation result,  since the script requires`image-dir` (I would like to know the specific way to do this step)

Thanks again for the great work, looking forward to your reply.

**Comment by heethesh** [comment]
Added [USAGE.md](https://github.com/heethesh/SALSA-Semantic-Assisted-SLAM/blob/master/docs/USAGE.md).
