### ISSUE TITLE
Problems with semantic labels rviz

### ISSUE THREAD

**Issue by DaddyWesker** [heethesh/SALSA-Semantic-Assisted-SLAM#6]
Hello.

THanks for your code. I was able to launch salsa on mono euroc data but i've got some strange results. Here
![Euroc_salsa_example](https://user-images.githubusercontent.com/10774222/124753625-e1d29d00-df31-11eb-8b0c-8b3ab85a3281.png)

THing is that there are like no semantic labels on the pointcloud. Just white points. I'm launching eouroc bag, which i've updated with segmentation as it said in FAQ, using commands:
`rosbag play V1_01_easy_segment.bag /cam0/image_raw:=/d400/color/image_raw /cam0/dynamic_scores:=/d400/annotation/dynamic_scores`
`roslaunch orb_slam2_ros salsa.launch` (by the way. In your FAQ it is orb_slam_2_ros which is incorrect in my case).

ANy suggestions what i'm doing wrong to see semantically labelled pointcloud?

**Comment by heethesh** [comment]
I don't think we visualized the semantic labels on the point cloud, it was only the ORB features that were colored on the image. You can try to publish a RGB point cloud and set the color if you want to visualize them.

**Comment by DaddyWesker** [comment]
Thanks for the answer. I'm seeing here https://raw.githubusercontent.com/heethesh/SALSA-Semantic-Assisted-SLAM/master/docs/results.png some colored 3d points. That was just orb features as you said? I thought it is the semantic labels.

**Comment by heethesh** [comment]
that just looks like x/y/z axes visualized

**Comment by DaddyWesker** [comment]
Got it. THanks. I guess i'm closing the issue then.
